apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helm-deployments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: deploy-helm CD jobs
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: helm-deployments-dev
    server: https://kubernetes.default.svc
  - namespace: helm-deployments-stg
    server: https://kubernetes.default.svc
  - namespace: helm-deployments-prd
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except namespace
  clusterResourceWhitelist: 
  - group: ''
    kind: Namespace
  # Allow namespaced-scoped resources to be created
  namespaceResourceBlacklist: []
  # Deny namespaced-scoped resources from being created except for these
  namespaceResourceWhitelist: 
  - group: 'apps'
    kind: Deployment
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'
  - group: 'networking.k8s.io'
    kind: 'Ingress'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: 'ServiceAccount'
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
  roles: []
  # A role which provides sync privileges to only the backoffice-portal application
  # - name: ci-role
  #   description: Sync privileges for backoffice-portal
  #   policies:
  #   - p, proj:backoffice-portal:ci-role, applications, sync, backoffice-portal/backoffice-portal, allow