replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable
env:
- name: ECHO_LABEL
  value: Este eh um container para testes em dev
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
  - host: umtestequalquer-dev.com.br
    paths:
    - path: /
      pathType: Prefix
  tls: []
# resources:
#   limits:
#     cpu: 64m
#     memory: 64m
#   requests:
#     cpu: 64m
#     memory: 64m
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
